# Generated by Django 3.1.4 on 2020-12-13 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='field',
        ),
        migrations.AddField(
            model_name='query',
            name='query_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='url',
            field=models.URLField(default='google.com', max_length=250),
        ),
    ]
