# Generated by Django 3.1.4 on 2020-12-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_auto_20201213_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
