# Generated by Django 3.1.4 on 2020-12-13 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='query',
            name='httpcode',
            field=models.TextField(default='404', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='ipaddress',
            field=models.GenericIPAddressField(default='www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='query_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='timeout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='query',
            name='url',
            field=models.URLField(default='google.com', max_length=250),
        ),
    ]
