# Generated by Django 3.1.4 on 2020-12-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20201213_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='ipaddress',
            field=models.TextField(max_length=250),
        ),
    ]
